checkPointPath: '/kaggle/working/'
output: '/kaggle/input/pthfile/epoch80_89.41.pth'
globalFeature: True
regionFeature: False
device:
trainOrVal:
train:
    seed: 0
    learningRate: 0.0001
    weight_decay: 0
    lr_plan: 0.0001
    epoch: 0
    startEpoch: 0
    totalEpochs: 150
    criterion: ce_loss
    scheduler:
        epochs: 30
        milestones: [ 10,150 ]
        gamma: 0.1
    optimizer:
        type: Adam
        kwargs:
            lr: 0.0001
    print_freq: 50
    pretrain: null
val:
    weightFile:
numMaxN: 12
dataset:
    data_name: 'volleyball'
    num_frames: 8
    image_size: [720, 1280]
    out_size: [87, 157]
    workers: 1
    data_path: 'data/collective-augmented'
    num_before: 5
    num_after: 4
    train:
        sample: 'train'
        batch_size: 1
        flip: true
        data_path: '/kaggle/input/volleyball/videos-train/videos-train' # include flow
        tracks: '/kaggle/input/volleyball/videos-train/videos-train/tracks_normalized.pkl'
        keypoints: '/kaggle/input/volleyball/volleyball_result_kpt.json'
        seqs: [ 1,3,6,7,10,13,15,16,18,22,23,31,32,36,38,39,40,41,42,48,50,52,53,54,0,2,8,12,17,19,24,26,27,28,30,33,46,49,51 ]
    val:
        sample: 'val'
        batch_size: 1
        flip: false
        data_path: '/kaggle/input/volleyball/videos-val/videos-val' # include flow
        tracks: '/kaggle/input/volleyball/videos-train/videos-train/tracks_normalized.pkl'
        keypoints: '/kaggle/input/volleyball/volleyball_result_kpt.json'
        seqs: [4,5,9,11,14,20,21,25,29,34,35,37,43,44,45,47]
crop_size: [7,7]
structure:
    crop_h: 5
    crop_w: 5
embed_features: 512
encoderLayersNum: 1
decoderLayersNum: 1
headNum: 8
dropoutNum: 0.1
numLayers: 1
actionsMumClasses: 9
activitiesNumClasses: 8
actionsLossWeight: 1
spatial_encoding: False
globalGAR:
    embedChannel: 512
    tokenNum: 16
    tokenFeatureDim: 512
    tokenInchannel: 2048
    numEncoderLaters: 2
    headNum: 8
    dropoutNum: 0.1