outputPath: '/kaggle/working/'
checkPointPath: 'pth/epoch55_98.03%.pth'
#checkPointPath: '/kaggle/input/pthfile/epoch120_95.42.pth'
#checkPointPath: '/kaggle/input/pthfile/epoch100_93.99.pth'
resultPath: '/kaggle/working/'
device:
trainOrVal:
crop_size: [5,5]
embed_features: 512
encoderLayersNum: 3
decoderLayersNum: 0
headNum: 8
dropoutNum: 0.1
numLayers: 1
actionsMumClasses: 6
groupNumClasses: 6
activitiesNumClasses: 5
actionsLossWeight: 1.0
spatial_encoding: True
KEYT: 4
MAXEpoch: 150
numMaxN: 13
logPath: '/kaggle/working/log.txt'
train:
    seed: 0
#    lr: 0.0001
#    lr_plan: {21:1e-4, 41:5e-5, 81:1e-5}
#    weight_decay: 0.001
    actions_weight: [ 1., 1., 2., 3., 1.,2.]
    group_weight: [ 1., 1., 1., 1.,1.,1. ]
    activities_weight: [ 1., 1., 1., 1.,1.]
    epoch: 0
    startEpoch: 0
    totalEpochs: 150
    criterion: ce_loss
    scheduler:
        epochs: 150
        milestones: [ 20,150 ]
        gamma: 0.1
    optimizer:
        type: Adam
        kwargs:
            lr: 0.0001
    print_freq: 50
    pretrain: null
val:
    weightFile:
dataset:
    num_frames: 10
    image_size: [480, 720]
    out_size: [15, 23]
    workers: 1
    data_name: collective
    #data_path: '/kaggle/input/collective-augmented/collective-augmented'
    data_path: 'data/SCCAD'
    train:
        batch_size: 2
        sample: 'train'
        flip: true
        seqs: [1, 2, 3, 4, 12, 13, 14, 17, 18, 19, 20, 21, 22, 23, 24, 26, 27, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42]
        #seqs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 16, 25, 28, 29, 52, 53, 59, 60, 64, 66, 68, 70, 71, 12, 13, 14, 17, 18, 19, 20, 21, 22, 23, 24, 26, 27, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 54, 55, 56, 57, 58, 61, 62, 63, 65, 67, 69, 72]
    val:
        batch_size: 2
        sample: 'val'
        flip: false
        seqs: [5, 6, 7, 8, 9, 10, 11 ,15, 16, 25, 28, 29 ]
        #seqs: [ 5, 6, 7, 8, 9, 10, 11, 15, 16, 25, 28, 29, 52, 53, 59, 60, 64, 66, 68, 70, 71]
